version: '3.8'

services:
  app:
    build: .
    container_name: backend-feathers
    ports:
      - '3030:3030'
    environment:
      MONGODB_URL: mongodb://mongodb:27017/AMD201-WasteSort
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/backend-feathers
    command: npm start

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  
volumes:
  mongodb_data:
